Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MrsTaster.Data.Repository;
using MrsTaster.Models;
using MrsTaster.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MrsTaster.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
       
        public PanelController(IRepository repo)
        {
            _repo = repo;
            
        }

        public IActionResult Index()
        {
            var posts = _repo.GetAllPost();

            return View(posts);
        }

        public IActionResult Post(int id)
        {
            PostViewModel model = new PostViewModel();
            model.GetPost = _repo.GetPost(id);
            model.Title = model.GetPost.Title;
            model.Body = model.GetPost.Body;

            model.CurrentCategory = _repo.GetCategory(model.GetPost.CategoryId).CategoryName;

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit()
        {
            PostViewModel model = new PostViewModel();

            List<Category> categories = _repo.GetCategories();

            model.CategoryList = (from c in categories
                                  select new SelectListItem
                                  {
                                      Text = c.CategoryName,
                                      Value = c.CategoryId.ToString()
                                  }).ToList();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PostViewModel viewpost)
        {
            Post post = new Post();
            post.Title = viewpost.Title;
            post.Body = viewpost.Body;            
            post.CategoryId = int.Parse(viewpost.CurrentCategory);
            post.Created = viewpost.Created;
            _repo.AddPost(post);

            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");

            else
                return View(post);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Search()
        {
            PostViewModel model = new PostViewModel();

            List<Category> categories = _repo.GetCategories();

            model.CategoryList = (from c in categories
                                  select new SelectListItem
                                  {
                                      Text = c.CategoryName,
                                      Value = c.CategoryId.ToString()
                                  }).ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(PostViewModel values)
        {
            PostViewModel model = new PostViewModel();


            model.SearchPosts = _repo.FindPost(values.SearchValue, int.Parse(values.CurrentCategory));


            return View(model);

        }
    }
}

Views/Panel/Edit.cshtml
@model MrsTaster.ViewModels.PostViewModel

@{

}

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
<script src="~/JS/MyJSfile.js" defer></script>

<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="PostId" type="hidden" />
        <div>
            <label>Title</label>
            <input asp-for="Title" maxlength="50" />
            <span asp-validation-for="Title"></span>
        </div>
        <div>
            <label>Body</label>
            <input asp-for="Body" maxlength="2000" />
            <span asp-validation-for="Body"></span>
        </div>

        <div>
            <label>Category</label>
            <select asp-for="@Model.CurrentCategory" asp-items="@Model.CategoryList"></select>

        </div>
       
        <div>
            <label>Created</label>
            <input asp-for="Created" />
        </div>
        <input type="submit" value="Submit" />
    </form>
</div>

Views/Panel/Index.cshtml
@model IEnumerable<MrsTaster.Models.Post>

@{

}

<h3>Admin panel!</h3>

<div>
    <ul>
        @foreach (var post in Model.OrderBy(item => item.Created))
        {
        <li>
            @post.Title @post.Created
            -
            <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.PostId">
                Edit post
            </a>
            -
            <a asp-controller="Panel" asp-action="Delete" asp-route-id="@post.PostId">
                Delete post
            </a>
        </li>
        }
    </ul>
</div>